### PR TITLE
Small cleanup (use proper generics and remove several compiler warnings)

### PR DESCRIPTION
**Pull request by ivmarkov**
The subject says it all.
One minor addition: 3 of the examples (your TodoMVC, Redux Counter and MobXTodoMVC) did not work because there were React components in there with missing @JsType annotation. Not sure hiw it has worked for you that way...

### CODE REVIEW

**Comment by pstockley** [comment]
That's really strange. Everything compiles fine for me including SDM. I am using Intellij.  What are you using?

**Comment by pstockley** [comment]
Intellij uses the javac compiler by default.

**Comment by ivmarkov** [comment]
If you mean the missing @JsType annotations - the mentioned projects do compile, but do not *run*. And I'm at a loss how they can run for you, given that it is indeed an error to omit the @JsType annotation for React stateful components as that results in GWT mangling of the method names from e.g. 'render' to 'render_g$' - which - in turn - means that React - in devmode - complains that your component does not have a 'render' method.

**Comment by pstockley** [comment]
Do you have -generateJsInteropExports set on SDM

**Comment by ivmarkov** [comment]
Yes. Without it, everything will be mangled. Even the types annotated with @JsType.

**Comment by pstockley** [comment]
Let me look into it. Perhaps my last set of changes broke something. Once I get it resolved, I will merge your changes.

**Comment by ivmarkov** [comment]
Wow. Just found the reason - it is me after all. Sneaky JSInterop!

I've changed the visibility of  two abstract methods, 
ReactClassSpec.render() and ReactClassSpec.getInitialState() from public to protected because the @flow annotations in React indicate that they should be considered protected.

What I forgot to realize is that even though ReactClassSpec is annotated with @JsType, these two abstract methods *will* nevertheless be mangled, because they are protected rather than public now.
There are two solutions:
* Restore their public visibility
* Keep them protected, but explicitly annotate them with with @JsMethod

I'm inclined for the latter, what do you think?

P.S. How does that relate to the missing @JsType annotation in e.g. your example Counter.java? Even though it is missing in your example code, the 'Counter.render' method is not mangled by GWT, because it *overrides* the ReactClassSpec.render method, which should be exported. Happy coincidence so to say.

**Comment by pstockley** [comment]
That makes sense now. I would annotate them with @JsMethod

**Comment by ivmarkov** [comment]
Done.

**Pull request merged**
